const env = {
    APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    API_URL: process.env.NEXT_PUBLIC_API_URL,
    API_GATEWAY_URL: process.env.NEXT_PUBLIC_API_GATEWAY_URL,
    URL_PREFIX: process.env.NEXT_PUBLIC_URL_PREFIX || '/api/v1',

    NODE_PORT: Number.parseInt(process.env.NODE_PORT || '3000', 10),
    NODE_ENV: process.env.NODE_ENV,
    APP_ENV: process.env.APP_ENV,

    TN_ANALYTICS_ENABLE: process.env.NEXT_PUBLIC_TN_ANALYTICS_ENABLE === 'true',
    TN_ANALYTICS_FIREHOSE_STREAM_NAME: process.env.NEXT_PUBLIC_TN_ANALYTICS_FIREHOSE_STREAM_NAME || '',
    TN_ANALYTICS_REGION: process.env.NEXT_PUBLIC_TN_ANALYTICS_REGION || '',
    TN_ANALYTICS_ACCESS_KEY: process.env.TN_ANALYTICS_ACCESS_KEY || '',
    TN_ANALYTICS_SECRET_KEY: process.env.TN_ANALYTICS_SECRET_KEY || '',
    TN_ANALYTICS_IDENTITY_POOL_ID: process.env.TN_ANALYTICS_IDENTITY_POOL_ID || '',
    TN_ANALYTICS_PROVIDER_NAME: process.env.TN_ANALYTICS_PROVIDER_NAME || '',
    TN_ANALYTICS_ENCRYPTION_KEY: process.env.TN_ANALYTICS_ENCRYPTION_KEY || '',
    TN_ANALYTICS_BACKEND_TOKEN: process.env.TN_ANALYTICS_BACKEND_TOKEN || '',
    TN_ANALYTICS_TRACK_TYPE: 'all',
    TN_ANALYTICS_FIREHOSE_TIMER: 300,
    TN_ANALYTICS_ENDPOINT: '/api/tn-analytics',
    TN_ANALYTICS_RETURN_IP_ADDRESS: false,

    GOOGLE_ANALYTICS_ENABLE: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ENABLE === 'true',
    GOOGLE_TAG_MANAGER_ID: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID ?? '',

    K8S_TERMINATION_GRACE_PERIOD_MS: Number.parseInt(process.env.K8S_TERMINATION_GRACE_PERIOD_MS || '30000', 10),

    NEW_RELIC_AGENT_ENABLED: process.env.NEW_RELIC_AGENT_ENABLED === 'true',
}

export default env